apiVersion: v1
kind: Pod
metadata:
  labels:
    hack: softinstall
  name: softinstall
  namespace: hackingdemo
spec:
  containers:
  - name: softinstall
    image: ubuntu
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;sleep 600
    startupProbe:
      exec:
        command:
        - apt-get
        - update
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 30
    readinessProbe:
      exec:
        command:
        - apt-get
        - install
        - -y
        - curl
      initialDelaySeconds: 30
      periodSeconds: 100
      timeoutSeconds: 60
