apiVersion: v1
kind: Pod
metadata:
   name: xssprobing
   namespace: hackindemo
   labels:
      hack: xssprobing
spec:
  containers:
  - name: radarhack
    image: docker.io/xxradar/naxsi5
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        host: www.xxxx.com
        path: /?'OR 1=1--
        port: 8080
        httpHeaders:
          - name: User-Agent
            value: xxxxxxxxx
